### ISSUE TITLE
Start times not displaying correctly

### ISSUE THREAD

**Issue by dathbe** [mumblebaj/MMM-PGA#2]
The start times/thru column isn't showing up right on my installation.  It will basically either show "F" for a completed round or "12:00 am" for an unfinished round -- whether in progress or upcoming.  Is that an issue with my installation or is it a bug in the code?

**Comment by dathbe** [comment]
It seems to be a logic issue in espn.js.  I'm not really clear on how multiple `return` statements in the same function work logically, so I've updated it to just conditionally return a single value in a fork.  Here's my logic:

```js
    getPlayerThru: function (player) {

        var displayValue = player.status.displayValue;
        var append = (player.status.startHole == "1") ? "" : "*";

        var teeTime = moment(displayValue, "YYYY-MM-DD HH:mm:ss Z");
        if (typeof displayValue == 'undefined' || displayValue == null) {

            returnValue = player.status.displayThru + append;

        } else if (displayValue == "F") {
            returnValue = displayValue;
        } else if (player.status.thru <= 17 && player.status.thru >= 1) {
            returnValue = displayValue + append;
        } else if (teeTime.isValid()) {
            returnValue = teeTime.local().format("h:mm a") + append;
        } else {
            returnValue = displayValue;
        }

        return returnValue;
    },
```

I'm currently testing.  It seems to work for players in progress (e.g. "Thru 12") and players who have finished (e.g., "F").  I don't have a player who has not started to test yet, so I'll try it when I can catch one.

If you want, I can create a PR.

**Comment by dathbe** [comment]
It seems to work with start times as well.  Not sure if there are other use cases--or if you're maintaining this anymore--but let me know if you want me to merge my fork.

**Comment by mumblebaj** [comment]
I have updated as per request and pushed new version.

**Comment by dathbe** [comment]
I'm still getting issues.  We were editing at the same time, but let me update my PR and you can look.

**Comment by mumblebaj** [comment]
Maybe move your version and do a fresh install?

**Comment by dathbe** [comment]
I've updated PR #3 , which is working for me.  Though I am still getting errors in my log.  I will create a separate PR for those.

```sh
0|mm  | [2025-04-11 10:46:12.646] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'rankings')
0|mm  |     at Object.getOWGRData (~/MagicMirror/modules/MMM-PGA/OWGR.js:28:29)
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
0|mm  | (Use `electron --trace-warnings ...` to show where the warning was created) 
0|mm  | [2025-04-11 10:46:12.649] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) 
0|mm  | [2025-04-11 10:46:12.682] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'rankings')
0|mm  |     at Object.getFedExCupData (~/MagicMirror/modules/MMM-PGA/FEDEXCUP.js:33:29)
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
0|mm  | [2025-04-11 10:46:12.684] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2) 
0|mm  | [2025-04-11 10:46:12.739] [LOG]   MMM-PGA config received 
0|mm  | [2025-04-11 10:46:12.740] [LOG]   ESPN MMM-PGA retrieving Tournament Data 
0|mm  | [2025-04-11 10:46:12.765] [LOG]   FEDEX MMM-PGA retrieving FedEx Cup Standings 
0|mm  | [2025-04-11 10:46:13.027] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'rankings')
0|mm  |     at Object.getOWGRData (~/MagicMirror/modules/MMM-PGA/OWGR.js:28:29)
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
0|mm  | [2025-04-11 10:46:13.030] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3) 
0|mm  | [2025-04-11 10:46:13.047] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'rankings')
0|mm  |     at Object.getFedExCupData (~/MagicMirror/modules/MMM-PGA/FEDEXCUP.js:33:29)
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
0|mm  | [2025-04-11 10:46:13.050] [ERROR] (node:7437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4) 
```

**Comment by dathbe** [comment]
It seems as though the issue is that your module is assuming every user wants rankings displayed, and I don't.  So my fixes handle the case where the user does not want rankings.

**Comment by mumblebaj** [comment]
I do not get any of those errors even if i set `showRankings: false,`

I am not sure why you are seeing the errors you are and I am not seeing anything.

**Comment by mumblebaj** [comment]
I get the following with you suggested fix:

![Image](https://github.com/user-attachments/assets/985cb6c3-73fc-4c4c-8725-a4d2b79b8c72)

When I start there is no errors.

```
> magicmirror@2.31.0 start
> npm run start:x11


> magicmirror@2.31.0 start:x11
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2025-04-11 20:04:30.956] [LOG]   Starting MagicMirror: v2.31.0
[2025-04-11 20:04:30.977] [LOG]   Loading config ...
[2025-04-11 20:04:30.979] [LOG]   config template file not exists, no envsubst
[2025-04-11 20:04:31.260] [INFO]  Checking config file /home/mumble/MagicMirror/config/config.js ...
[2025-04-11 20:04:31.339] [INFO]  Your configuration file doesn't contain syntax errors :)
[2025-04-11 20:04:31.340] [INFO]  Checking modules structure configuration ...
[2025-04-11 20:04:31.413] [INFO]  Your modules structure configuration doesn't contain errors :)
[2025-04-11 20:04:31.415] [LOG]   Loading module helpers ...
[2025-04-11 20:04:31.419] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.420] [LOG]   Check MagicMirror² version for node helper 'MMM-GasMonitor' - Minimum version: 2.22.0 - Current version: 2.31.0
[2025-04-11 20:04:31.420] [LOG]   Version is ok!
[2025-04-11 20:04:31.421] [LOG]   Module helper loaded: MMM-GasMonitor
[2025-04-11 20:04:31.545] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.545] [LOG]   Check MagicMirror² version for node helper 'MMM-PGA' - Minimum version: 2.20.0 - Current version: 2.31.0
[2025-04-11 20:04:31.545] [LOG]   Version is ok!
[2025-04-11 20:04:31.545] [LOG]   Module helper loaded: MMM-PGA
[2025-04-11 20:04:31.546] [LOG]   No helper found for module: MMM-SweepClock.
[2025-04-11 20:04:31.547] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.547] [LOG]   Module helper loaded: MMM-NOAA3
[2025-04-11 20:04:31.666] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.666] [LOG]   Check MagicMirror² version for node helper 'MMM-WOTD' - Minimum version: 2.22.0 - Current version: 2.31.0
[2025-04-11 20:04:31.666] [LOG]   Version is ok!
[2025-04-11 20:04:31.666] [LOG]   Module helper loaded: MMM-WOTD
[2025-04-11 20:04:31.712] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.712] [LOG]   Check MagicMirror² version for node helper 'MMM-Growatt' - Minimum version: 2.22.0 - Current version: 2.31.0
[2025-04-11 20:04:31.712] [LOG]   Version is ok!
[2025-04-11 20:04:31.713] [LOG]   Module helper loaded: MMM-Growatt
[2025-04-11 20:04:31.764] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.764] [LOG]   Check MagicMirror² version for node helper 'MMM-Growatt-Stats' - Minimum version: 2.23.0 - Current version: 2.31.0
[2025-04-11 20:04:31.764] [LOG]   Version is ok!
[2025-04-11 20:04:31.764] [LOG]   Module helper loaded: MMM-Growatt-Stats
[2025-04-11 20:04:31.765] [LOG]   No helper found for module: MMM-pages.
[2025-04-11 20:04:31.765] [LOG]   No helper found for module: MMM-page-indicator.
[2025-04-11 20:04:31.765] [LOG]   No helper found for module: alert.
[2025-04-11 20:04:31.768] [LOG]   Initializing new module helper ...
[2025-04-11 20:04:31.768] [LOG]   Module helper loaded: updatenotification
[2025-04-11 20:04:31.768] [LOG]   All module helpers loaded.
[2025-04-11 20:04:31.773] [LOG]   Starting server on port 8080 ...
[2025-04-11 20:04:32.337] [LOG]   Server started ...
[2025-04-11 20:04:32.338] [LOG]   Connecting socket for: MMM-GasMonitor
[2025-04-11 20:04:32.338] [LOG]   Starting NodeHelper for MMM-GasMonitor
[2025-04-11 20:04:32.339] [LOG]   Connecting socket for: MMM-PGA
[2025-04-11 20:04:32.339] [LOG]   Starting node_helper for: MMM-PGA
[2025-04-11 20:04:32.341] [LOG]   Connecting socket for: MMM-NOAA3
[2025-04-11 20:04:32.341] [LOG]   Connecting socket for: MMM-WOTD
[2025-04-11 20:04:32.342] [LOG]   Starting node_helper for: MMM-WOTD
[2025-04-11 20:04:32.342] [LOG]   Connecting socket for: MMM-Growatt
[2025-04-11 20:04:32.343] [LOG]   Starting node helper for MMM-Growatt
[2025-04-11 20:04:32.343] [LOG]   Connecting socket for: MMM-Growatt-Stats
[2025-04-11 20:04:32.343] [LOG]   Starting node helper for MMM-Growatt-Stats
[2025-04-11 20:04:32.344] [LOG]   Connecting socket for: updatenotification
[2025-04-11 20:04:32.344] [LOG]   Starting module helper: updatenotification
[2025-04-11 20:04:32.344] [LOG]   Sockets connected & modules started ...
[2025-04-11 20:04:32.445] [LOG]   Launching application.
[2025-04-11 20:04:33.682] [LOG]   Writing 86.80 to /home/mumble/MagicMirror/modules/MMM-GasMonitor/input.txt
[2025-04-11 20:04:33.758] [LOG]   FEDEX MMM-PGA retrieving FedEx Cup Standings
[2025-04-11 20:04:33.907] [INFO]  updatenotification: Updater Class Loaded!
[2025-04-11 20:04:33.908] [INFO]  updatenotification: Checking PM2 using...
[2025-04-11 20:04:33.909] [INFO]  updatenotification: [PM2] You are not using pm2
[2025-04-11 20:04:33.913] [INFO]  Checking git for module: MMM-GasMonitor
[2025-04-11 20:04:33.939] [INFO]  Checking git for module: MMM-PGA
[2025-04-11 20:04:33.965] [INFO]  Checking git for module: MMM-SweepClock
[2025-04-11 20:04:33.990] [INFO]  Checking git for module: MMM-NOAA3
[2025-04-11 20:04:34.016] [INFO]  Checking git for module: MMM-WOTD
[2025-04-11 20:04:34.036] [INFO]  Checking git for module: MMM-Growatt
[2025-04-11 20:04:34.062] [INFO]  Checking git for module: MMM-Growatt-Stats
[2025-04-11 20:04:34.084] [INFO]  Checking git for module: MMM-pages
[2025-04-11 20:04:34.106] [INFO]  Checking git for module: MMM-page-indicator
[2025-04-11 20:04:34.133] [INFO]  Checking git for module: MagicMirror
[2025-04-11 20:04:39.305] [INFO]  Update found for module: MMM-GasMonitor
[2025-04-11 20:04:39.306] [INFO]  Update found for module: MMM-PGA
[2025-04-11 20:04:39.306] [INFO]  Update found for module: MMM-WOTD
[2025-04-11 20:04:39.306] [INFO]  Update found for module: MMM-Growatt
[2025-04-11 20:05:08.398] [INFO]  System information:
### SYSTEM:   manufacturer: Microsoft; model: WSL; virtual: true
### OS:       platform: linux; distro: Ubuntu; release: 20.04.6 LTS; arch: x64; kernel: 5.15.167.4-microsoft-standard-WSL2
### VERSIONS: electron: 35.1.2; used node: 22.14.0; installed node: 22.14.0; npm: 10.9.2; pm2: 5.4.3
### OTHER:    timeZone: Africa/Johannesburg; ELECTRON_ENABLE_GPU: undefined
^C/home/mumble/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
```

Either you are not using the correct version or something else is not working as expected.
Latest version of module is 1.3.2.

**Comment by mumblebaj** [comment]
Also check if you on the master

![Image](https://github.com/user-attachments/assets/6745d8d2-1650-4f7a-ba42-14c61552448a)

**Comment by dathbe** [comment]
You aren't getting errors because you still have a valid `RapidAPIKey` set.  Your module tries to fetch rankings data even if `showRankings` is `false`.  Fixed with #4

**Comment by dathbe** [comment]
In fact, we could update the logic one more level to not fetch rankings if showRankings is false _even if_ an API key is set.  Let me know if you prefer that approach to avoid unecessary api calls.

**Comment by dathbe** [comment]
I made the executive decision that triggering the rankings API calls off `showRankings` is the objectively better method.  This way users will receive an error if showRankings is set to true, but the API key is unset or set incorrectly (i.e., if the user appears to want rankings data even though settings are incorrect to do it properly).  All included in #4

**Comment by mumblebaj** [comment]
I have added a comment on your PR. Review and update according. Easier to put the check in the socketNotificationReceived in the node_helper.js rather than updating both OWGR and FEDEXCUP.

**Comment by dathbe** [comment]
Done
